# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogsdb
    username: openpg
    password: openpgpwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    generate-ddl: true # Spring Boot will generate the necessary DDL scripts to create or update the database schema during application startup.
    database-platform: org.hibernate.dialect.PostgreSQLDialect #ensure that Hibernate generates the appropriate SQL statements and uses the correct syntax for PostgreSQL
    defer-datasource-initialization: true #We need Hibernate to create our tables before inserting the data into them.
  sql:
    init:
      mode: always
server:
  port: 7777
logging:
  level:
    org.springframework.security.web: DEBUG

